services:
  postgres:
    image: postgres:16-alpine
    container_name: payflow-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: payflow
      POSTGRES_PASSWORD: payflow_dev_2024
      POSTGRES_DB: payflow
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: payflow-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
